spring:
  application:
    name: geraldine
  datasource:
    url: jdbc:mysql://uvduld8bgi3pvxjc:WmME65zPfvvDX7dYIfjF@blensvglwp8woytvzjgp-mysql.services.clever-cloud.com:3306/blensvglwp8woytvzjgp?useSSL=false
    username: uvduld8bgi3pvxjc
    password: WmME65zPfvvDX7dYIfjF
  #  driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
